// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piaxcpwnltthcmjocwnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYXhjcHdubHR0aGNtam9jd25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQ0MjksImV4cCI6MjA3MTQ3MDQyOX0.ZLh9pe1BwPaPm7MZWh3PEL1OgDo7RGGZvtgktkfHgIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});